OpenHD/Open.HD

wifibroadcast-osd/ltm.c

home_altitude Error definition td->ltm_home_latitude!

ltm.c  Error definition

---

wifibroadcast-scripts/rx_functions.sh

Relay forwarding the stream have to first initializing the sharedmem for the tx_rawsock.

Relay mode fix

---

RemoteSettings/Ground/RemoteSettingsSync.py
wifibroadcast-osd/render.c
wifibroadcast-scripts/gpio-config.py

Feel free to integrate it back to development branch as needed.

Fix gpio selection for air sync, fix OSD render of total items

---

wifibroadcast-osd/ltm.c

Adopt the new altitude name for LTM osd

---

wifibroadcast-osd/frsky.c

Adopt the new altitude name for frsky osd

---

wifibroadcast-osd/smartport.c

Adopt the new altitude name for smartport osd

---

wifibroadcast-osd/render.c

Added support for Q-PLANE ArduPilot modes.

Update render.c to Q-PLANE flight modes

---

wifibroadcast-scripts/tx_functions.sh

Rtl8812au with mcs=N and CTS_PROTECTION =N does not work properly (low speed mode, rate ≈1mb/s)
PS：Further inspection of the measurement module is required

Autodetect abnormal Settings for RTL8812au

---

wifibroadcast-base/rssirx.c
wifibroadcast-base/rssitx.c

Fix the osd exception caused by the update

Return to original rssitx,rssirx

---

wifibroadcast-scripts/hotspot_functions.sh

Add hotspot TX power setting

---

wifibroadcast-scripts/rx_functions.sh

After sdcard partion creation, mount was failing

SDCard Recording Fix

---

wifibroadcast-scripts/rx_functions.sh

Added commands to remount file system as read/write , make dir, then remount file system as read-only again

Sdcard recording fix part 2

---

wifibroadcast-scripts/rx_functions.sh

As with so much of this stuff there was a follow on problem that turned up. The intitial recording after creating partion and mounting was successful however on subsequent restarts the recording was not working because for some reason the new partition was not mounting.

SDCard record fix part 3

---

wifibroadcast-misc/LCD/MouseListener.c

This is just fixing the indentation levels and formatting in MouseListener.c.

Fix formatting and indentation in MouseListener

---

wifibroadcast-osd/render.c

Total distance parenthesis fix

---

wifibroadcast-osd/render.c

Revert "Total distance parenthesis fix"

---

openhd-camera/openhdvid

openhdvid is a drop-in replacement for raspivid that happens to have
a mavlink client included. The mavlink code is disabled at the moment
until we can properly implement commands and wire it up to something
on the air side

Add openhdvid script

---

wifibroadcast-rc-Ath9k/rctx.c

This change is from Thomas, it prevents sending invalid button values by looking for changes in button values over time. If the button values "twitch" for a single reading, that reading is ignored. However if the same values persist for more than one reading, it is considered valid and sent in an RC transmission.
Note that this change only applies to the current default "range" RC, not "encrypted" RC.
Also note that this change may have the unintended side effect of delaying single RC axis value readings by 2ms as the entire RC packet is not sent if those button values "twitch".

Guard against invalid button values in ath9k rctx

---

wifibroadcast-rc-Ath9k/rctx.c

This treats 2 consecutive buttons as a fake axis, to use as a 3-way switch without using a real proportional axis on the transmitter.

Add support for camera switching with buttons

---

wifibroadcast-scripts/video_save_functions.sh

This also replaces references to `avconv` with `ffmpeg`, as the `avconv` command is just a symlink to `ffmpeg` anyway.
Default format should probably be changed to mp4 soon.

Allow video save format to be changed in settings

---

wifibroadcast-scripts/tx_functions.sh

Cut bitrate in half for 30fps HDMI input card and imx290

---

wifibroadcast-osd/render.c

Add Arduplane takeoff flight mode to OSD

---

wifibroadcast-base/tx_rawsock.c

This should make the new bandwidth measurement support in `tx_rawsock` match the behavior of the older `tx_measure`.

Fix measure support in tx_rawsock

---

wifibroadcast-base/rx.c

The old code is counting all received data from every adapter, what we really want to know is the amount of data coming in from the *best* adapter at any given time.
This fixes the last remaining known issue with the new raw/FEC bandwidth display added a few days ago.

Only calculate received data from best adapter

---

wifibroadcast-base/rx_rc_telemetry_buf.c

Used for openhd microservice channel between ground and air. We don't want to interfere with the existing telemetry system, which uses shared memory by default.

Allow shm to be disabled in rx_rc_telemetry_buf

---

wifibroadcast-scripts/uplink_functions.sh

This enables a separate mavlink communication channel between the air and ground side, using OpenHDRouter at each end to transport mavlink messages to/from the GCS (QOpenHD) and microservices running on the air and ground pi.
The microservices are still under development but the GPIO service and the power service both should be working. The camera service is not yet implemented.

Set up dedicated mavlink channel for microservices

---

wifibroadcast-rc-Ath9k/airswitches.c
wifibroadcast-rc-Ath9k/lora.c
wifibroadcast-rc-Ath9k/rcswitches.c
wifibroadcast-rc-Ath9k/rctx.c
wifibroadcast-rc-Ath9k/rctxUDP_IN.c

Clean up RC code

---

wifibroadcast-base/tx_rawsock.c

Format tx_rawsock.c

---

wifibroadcast-base/tx_telemetry.c

Format tx_telemetry.c

---

wifibroadcast-base/wifibackgroundscan.c

Format wifibackgroundscan

---

wifibroadcast-base/rx_status.c

Format rx_status

---

JoystickIn/JoystickIn/processUDP.c

Format UDP joystick code

---

RemoteSettings/Ground/RemoteSettingsSync.py

These are unhelpful and are generally too long for the message size anyway.

Don't send raw exception traces to status service

---

config/config.txt

Add CM4 support by activating its USB like discribed in the documentation

Add CM4 support

---

wifibroadcast-scripts/global_functions.sh

Added one more pi4 model b03114. UNTESTED...

Global Functions- add new pi4 model

---

wifibroadcast-scripts/.profile
wifibroadcast-scripts/tx_functions.sh

More tolerant VEYE camera detection if other i2c device exist on bus 0 address 0x3X for wifibroadcast-script :
- .profile
- tx_functions.sh

More tolerant VEYE camera detection if other i2c device exist on bus 0 address 0x3X : V2

---

README.asciidoc

I have added some missing links (such as the license GPLv2, Raspbian, Linux Kernel) and did some text corrections.

Update readme docs.

---

config/openhd-settings-1.txt
wifibroadcast-scripts/tx_functions.sh

Added the extra VEYE settings based on what has been mapped in QOpenHD.

Update VEYE settings

---

Dockerfile-armhf-raspbian-buster
config/openhd-settings-1.txt
package.sh
wifibroadcast-scripts/camera_setup.sh
wifibroadcast-scripts/global_functions.sh
wifibroadcast-scripts/tx_functions.sh
wifibroadcast-scripts/tx_rx_functions.sh

Update settings for IMX307, Add profiles and break out camera setup.

Update VEYE Settings IMX307

---

openhd-status/src/main.cpp
openhd-telemetry/inc/endpoint.h
openhd-telemetry/src/router.cpp
openhd-telemetry/src/serialendpoint.cpp
openhd-telemetry/src/tcpendpoint.cpp
openhd-telemetry/src/udpendpoint.cpp
openhd-video/src/hotspot.cpp
wifibroadcast-scripts/dhcpevent_thread.sh

Updated script running when device connect to hotspot
Try to fix telemetry issue
QGC seems to work, might be more fixes needed to have a stable function.

Update to get telemetry and hotspot working

---

openhd-telemetry/src/router.cpp

TCP for microservice was not turned back on

Add missing update solve #576

---

openhd-video/src/gstreamerstream.cpp

This fix allow using manual pipelines, still the sink element is preserved as suggested by original developer

Fixes #521 issue that prevent adding manual pipelines

---

openhd-video/src/hotspot.cpp

Fixed missing file change

---

.drone.yml

Revert "Experiment with pull request trigger for drone.io"

---

.drone.yml

Revert the "Revert " :)

---

openhd-common/openhd-camera.hpp
openhd-system/inc/cameras.h
openhd-system/src/cameras.cpp
openhd-video/inc/gstreamerstream.h
openhd-video/src/cameramicroservice.cpp
openhd-video/src/gstreamerstream.cpp

adding the start of Veye compatibility with enabling the camera configuration

Veye compatibility

---

package.sh

Moved platform specific dependencies to fix current issues with building jetson images.

Dependency fix

---

openhd-system/src/cameras.cpp

Added in an i2cdetect command for Veye camera detection.

added i2cdetect for veye

---

OpenHD/ohd_common/del.txt
OpenHD/ohd_common/openhd-util.hpp
OpenHD/ohd_interface/inc/openhd-wifi.hpp
OpenHD/ohd_interface/src/DWifiCards.cpp
OpenHD/ohd_interface/src/USBTetherListener.cpp

For release, last minute wifi card discovery fixes / improvements

Consti test

---

.github/workflows/rpi.yml
.github/workflows/ubuntu20_build_test.yml
OpenHD/main.cpp

Not the cleanest way, propably you could edit the config file directly in c++-code, but I do it via bash ;)
Adds Libcamera/Raspbicamsrc-switching

Adds Libcamera/Raspbicamsrc-switching
