wifibroadcast-scripts/global_functions.sh

When using the same setup file for air, relay and ground, make sure that the relay receives the air transmit channel and the ground receives the relay transmit channel.

For air, relay and ground use the same setup file.

---

wifibroadcast-scripts/tx_functions.sh

RTL881[24] wifi card enable RC and uplink, UseMCS=Y and CTS_PROTECTION=N are required.EncryptionOrRange=Range Or Encryption can be either.

RTL881[24] wifi card RC uplink caused video packet loss FIX.

---

RemoteSettings/RemoteSettings.py

When apps read the ground station settings over UDP, the ground station will now send back an end delimiter (ConfigEnd=ConfigEnd) after it has sent all of the settings key/value pairs, which allows apps to know when they've actually received all of them.
Otherwise they have to use timers or assume that the ground station might send any value at any time, which makes it difficult to coordinate loading/saving indicators and other UI actions.
This change has been tested with released builds of the Android settings app and doesn't cause it to break or change behavior (it hardcodes all the settings values and ignores this entirely).

Send ConfigEnd=ConfigEnd to apps when done reading settings

---

wifibroadcast-base/rssirx.c
wifibroadcast-base/rssitx.c
wifibroadcast-base/rx.c

Automatic check wifi card type, for rtl8812au use 802.11n MCS 0 frame RTS package, and enable STBC,LDPC.Modify 1st byte of MAC (0x7F) uesd port number 63, original 0xFF for portnumber 127. Avoid conflict with svpcom n80211Header 0xFF.

Rssitx/rx enables 802.11n MCS based on card type

---

wifibroadcast-base/Makefile

Restore use radiotap instead of radiotap_rc

Fixed radiotap reference for compiling rx.c

---

wifibroadcast-scripts/hotspot_functions.sh

Only used when QOpenHD is running on the ground station itself, when running remotely it uses the same 5154 port as always.
The change is to avoid having to use the shared memory system directly from QOpenHD and to ensure the app works the same everywhere.
This change should not impact anything else, it is read-only with respect to the shared memory telemetry system on the ground station, and port 5155 is previously unused. The packet rate is slow so it shouldn't cause any increased load, and the packets will simply get dropped if QOpenHD isn't running.

Send telemetry to QOpenHD on 127.0.0.1:5155

---

RemoteSettings/RemoteSettings.py

Used by QOpenHD, which will refuse to reboot or shutdown when the drone is armed, and warns the user either way.
This commit has some security/safety implications, we might want to start advising users to change the hotspot password or have them set one at first boot.

Add support for remote reboot/shutdown

---

wifibroadcast-scripts/hotspot_functions.sh

This is just removing the 2nd "Hotspot Shutting Down in x" message, we had 2 of them.
The first uses the configured time from settings, then pauses for that length of time, then another message is shown saying it will shut down in 10 seconds.

Remove duplicate hotspot shutdown message

---

wifibroadcast-scripts/main.sh

This prevents the scripts from killing the OSD entirely just to display the "Ethernet connected. IP: x.x.x.x" message. It removes the message entirely (if we want to keep that I can push another commit restoring just the message).
This also fixes an issue previously discussed in issue #145 where the OSD starts twice whenever ethernet is connected, because this part of the script starts another OSD instance even when the original is still running (it fails to find the PID of the original for some reason).

Remove ethernet wbc_status messages

---

wifibroadcast-rc-Ath9k/rctx.c

**Don't merge this yet.**
These changes add a simple filtering system for the RC axis channels to deal with brief invalid values.
This is code that Thomas has been maintaining out-of-tree for months and re-porting for every release.
Additional discussion can be found in [EZ-WifiBroadcast/issues/166](https://github.com/rodizio1/EZ-WifiBroadcast/issues/166#issuecomment-437471906)

Add RC axis filtering

---

wifibroadcast-rc-Ath9k/rctx.c

This disables the new RC filtering code unless the setting for it in `joyconfig.txt` is uncommented, purely to avoid creating unexpected behavior until it can be tested in various setups.

Put RC filtering behind a setting

---

RemoteSettings/Ground/KillForwardRTPSecondaryCamera.sh
RemoteSettings/Ground/RxForwardSecondaryRTP.sh
RemoteSettings/Ground/RxForwardSecondaryRTPAndDisplayLocally.sh
RemoteSettings/dhcpeventThread.sh
wifibroadcast-scripts/alive_functions.sh
wifibroadcast-scripts/global_functions.sh
wifibroadcast-scripts/hotspot_functions.sh
wifibroadcast-scripts/main.sh
wifibroadcast-scripts/osd_rx_functions.sh
wifibroadcast-scripts/rssi_rx_functions.sh
wifibroadcast-scripts/rx_functions.sh
wifibroadcast-scripts/tether_functions.sh
wifibroadcast-scripts/uplink_functions.sh
wifibroadcast-scripts/video_save_functions.sh
wifibroadcast-status/Makefile
wifibroadcast-status/qstatus.c

This should preserve existing Open.HD behavior unless `ENABLE_QOPENHD=Y` in `openhd-settings-1.txt`
If the variable is missing from the settings file, it behaves as if `ENABLE_QOPENHD=N`.
This includes support for 2nd camera stream display but continues to use `hello_video` on the ground station for the primary video stream due to GStreamer jitter (affects every platform and occurs even without involving QOpenHD at all).

Add QOpenHD support behind a feature flag

---

wifibroadcast-scripts/hotspot_functions.sh

The builder is now installing it to /usr/local/bin so that we can delete the build directory and save 107MB of wasted space on the SD card

Update location of mavlink-routerd

---

wifibroadcast-scripts/global_functions.sh
wifibroadcast-scripts/main.sh

This avoids `/wbc_tmp` being too large and causing crashes or safety issues, which is possible on Pi3A+ and perhaps even Pi3B+ when GPU memory is increased beyond 128M.
In either case this change will prevent `/wbc_tmp` from ever using more than 1/4 of *available* ram plus an additional 30MB.

Dynamic wbc tmp

---

openhd-camera/openhdvid

Currently just rewrites the same file every time it runs, but will refuse to start if less than 10% disk space is available on the partition the file is being saved to, and will stop recording if free disk space falls below 10% at any time.
There are 3 new options:
`-wr` for the recording width (optional, defaults to 1280)
`-hr` for the recording height (optional, defaults to 720)
`-rec` or `--record` to enable recording and supply a location to save the video.
This should split and resize the video coming from the camera sensor *before* h264 encoding runs, and will start 2 separate encoders for each stream. Unless the GPU is unable to keep up the 2 streams should not affect each other. I have not tested this for latency yet.

add support for local recording in openhdvid

---

wifibroadcast-scripts/main.sh
wifibroadcast-scripts/tx_rx_functions.sh

This prevents the temp dir from being mounted several times due to
main.sh being run more than once (one for each tty).

Move wbc_tmp setup to tx_rx_functions.sh

---

RemoteSettings/KillRaspivid.sh
wifibroadcast-scripts/tx_functions.sh
wifibroadcast-scripts/uplink_functions.sh

This adds support for *optionally* using `openhdvid` instead of `raspivid` for the main camera. It is disabled by default.
To enable it, set `ENABLE_OPENHDVID=Y` in the `openhd-settings-1/2/3/4.txt` files.
When enabled, the system should behave exactly as it did before, all existing `raspivid` arguments are accepted by `openhdvid` as well, although not all of them *do* the same thing at the moment (some `raspivid` options aren't really useful to Open.HD in the first place).
When `openhdvid` is enabled you can optionally enable air-side video recording by adding the following arguments to `EXTRAPARAMS`:
-wr 1280 -hr 720 --record /home/pi/mainvideo.h264
Not that as of right now there is no way to automatically retrieve that recording except for using SSH or removing the SD card, but at some …

Add optional support for using openhdvid

---

openhd-camera/openhdvid
wifibroadcast-scripts/tx_functions.sh

* Write openhdvid log messages to stderr since stdout is supposed to be piped to tx_rawsock
* Disable stdout buffering
* Don't resize video in openhdvid if record resolution is the same as main stream resolution
* The PiCamera recording support can optionally resize the video, which occurs before the encoding step but may introduce additional latency. We want to try and eliminate any chance that the GPU will decide to add latency on the main stream.
* Add separate settings for openhdvid recording options
* Requires a separate PR for the builder to add these options to the default settings files

Openhdvid update

---

wifibroadcast-rc-Ath9k/rctx.c

The original code allocates 8 * uint16_t when JSSWITCHES isn't defined,
but 9 * uint16_t when JSSWITCHES is defined.
However there are spots in the code that write to rcData[8], which makes it look like you can do that all the time.
This change ensures that the available space in that array is always the same.

Always allocate rcData as 9 * uint16_t

---

RemoteSettings/RemoteSettings.py

This processes the `HOTSPOT_TXPOWER` setting whenever it is saved and immediately uses the value to change the hotspot power setting on the `wifihotspot0` interface. 
The setting still gets saved in the `openhd-settings-1.txt` file.
This prevents users from having to reboot the ground station just to change the hotspot power level.

Allow hotspot TX power to be changed live

---

wifibroadcast-osd/render.c

A float doesn't have enough precision for this equation, but a double does.
The original code is also using M/s divided by hours (time_diff in milliseconds divided by number of milliseconds per hour). It should be KM/h divided by hours to get total kilometers.

Fix total distance on OSD

---

wifibroadcast-base/rssitx.c
wifibroadcast-osd/render.c
wifibroadcast-scripts/tx_functions.sh

This causes the "set bitrate" display on the OSD to match the configured video bitrate if the user is not using auto bitrate.
This also shows "--" for the measured bitrate when the system is not doing an automatic bitrate measurement. Previously it was showing garbage values.

Fix manual bitrate display in OSD

---

wifibroadcast-osd/render.c

If auto bitrate is in use, turning the bitrate red in the OSD is helpful to indicate that real bitrate usage is approaching or has exceeded the measured available bitrate.
However when manual bitrate is in use, there is nothing to indicate what would be "too much" because there's no measurement to compare it with in the first place.
At the moment the OSD is saying "the bitrate you configured is too much" and that's not the case.
In the future we might want to still set this red based on some other criteria, or always measure available bandwidth periodically.

Don't use red color on bitrate if set manually

---

wifibroadcast-scripts/global_functions.sh
wifibroadcast-scripts/main.sh

This should automatically detect the imx290, check if `i2c_vc` is enabled in `config.txt`, and if not we enable it and immediately reboot.
This should prevent anyone from having to care about `i2c_vc` while also making it possible to avoid turning it on by default (it breaks the pi touchscreen and is a serious stability risk on the ground side)
**Note**: this is behind an intentionally undocumented setting for now. To test it, just put `AUTO_I2C_VC=Y` in `openhd-settings-1.txt` and boot the air side with an imx290 connected.
After we've tested this a bit it can be enabled all the time without a setting.

Automatically enable i2c_vc for imx290 if needed

---

wifibroadcast-base/tx_rawsock.c
wifibroadcast-scripts/tx_functions.sh

Use the argument "-z 1" (-m and -M are already used for other things).
This will allow us to get rid of the tx_measure program, which is 90% duplicated from an old version of tx_rawsock.

Add bandwidth measurement support to tx_rawsock

---

wifibroadcast-scripts/global_functions.sh
wifibroadcast-scripts/main.sh

The i2c_vc autoenable depends on knowing that an IMX290 is connected,
but there's no way to know that without already having i2c_vc enabled.
So there's essentially no way to fully automate it, but we can still
check for a `/boot/i2c_vc` file the same way Raspbian usually does for
`/boot/ssh` and `/boot/wpa_supplicant.conf`: just place an empty file in
the /boot partition called `/boot/i2c_vc`, and we will automatically ensure 
i2c_vc is enabled at boot.

Change auto i2c_vc to a boot file check

---

UDPSplitter/udpsplitter.py
wifibroadcast-scripts/UDPsplitterhelper.sh

A single python list is the only global state here, and python lists themselves are thread safe (we never modify list elements so the usual concern of data races is not an issue).
Exceptions in the 2 loops are intentionally ignored. Unless something goes wrong with the sockets themselves (which is unlikely but could be explicitly handled if necessary), they should just keep running.
Uses 6-11% CPU time in testing on a pi3+, profiling would help reduce that a bit more but it's not likely to be an issue.
Closes #150

Add safer Python implementation of UDPSplitter

---

wifibroadcast-scripts/main.sh

This is now unnecessary as the console is never turned off in the first place with https://github.com/OpenHD/Open.HD_Image_Builder/pull/121

Remove unnecessary console remapping in scripts

---

wifibroadcast-scripts/rx_functions.sh
wifibroadcast-scripts/video_save_functions.sh

Just set `VIDEO_TMP=none` in `openhd-settings-1.txt`, video will not be saved and the processes that run when inserting a USB stick will only save telemetry

Add support for disabling ground video recording

---

wifibroadcast-base/openhdlib.h
wifibroadcast-base/rssirx.c
wifibroadcast-base/rx.c
wifibroadcast-osd/main.c
wifibroadcast-osd/render.c
wifibroadcast-osd/render.h
wifibroadcast-osd/telemetry.h
wifibroadcast-scripts/rx_functions.sh

This changes the OSD on the ground station so that the video bitrate and radio data rate display make sense, and so that the real data rate from air -> ground (including FECs) is shown at all times.
The radio data line will now flash yellow if real data usage over the air exceeds the measured data rate or channel capacity, and will flash red if it exceeds 75% of the hardware data rate. That 75% is arbitrary, we may want to adjust it downward depending on testing.
**Note**: this PR does not send the new information to connected Android devices yet, this is due to the way the telemetry in OpenHD is being sent over the hotspot connection, it can't simply be altered without breaking existing apps. It can however be added soon without breaking anything.
The old OSD code shows the current …

Draw current/measure/max air rate, current/set video bitrate

---

wifibroadcast-base/tx_rawsock.c
wifibroadcast-scripts/tx_functions.sh

This ensures that the raw bandwidth measurement includes the correct total data rate based on the configured video packets + FEC packets, and prints the details of how we arrived at the final video bitrate in the terminal on the air side.

Move video/FEC calculation out of tx_rawsock

---

wifibroadcast-osd/mavlink.c

This is the same problem that affected QOpenHD, when you have QGC running somewhere it sends its own heartbeats, which the OSD is interpreting and using to change the flight mode and arm state shown on the display.
This is only a quick fix, a real fix would be to validate the heartbeat message.

Fix QGC heartbeat making OSD change flight mode

---

JoystickIn/JoystickIn/processUDP.c
RemoteSettings/Ground/helper/JoystickSender.c
RemoteSettings/Ground/helper/build.sh
wifibroadcast-base/openhdlib.h
wifibroadcast-base/rx_rc_telemetry.c
wifibroadcast-base/rx_rc_telemetry_buf.c
wifibroadcast-rc-Ath9k/airswitches.c
wifibroadcast-rc-Ath9k/rcswitches.c
wifibroadcast-rc-Ath9k/rctx.c
wifibroadcast-rc-Ath9k/rctxUDP_IN.c

The old code was hardcoding the RC struct memory layout on the air side as if the incoming RC packet data was 13 bytes long and contained data for 16 switches, ignoring the `JSSWITCHES` setting in `joyconfig.txt`.
The ground side however was honoring the setting and only sending the proper number of bits to the air side in RC packets.
The air side was therefore reading past the end of the packet in memory and sending garbage values to the flight controller.
Further, the settings file claimed you could send either 8 or 16 switches, but this was totally impossible as we are always sending 8 axis channels, leaving only another 10 possible for Mavlink and none of the other RC protocols were being given switch data at all.

Fix rc buttons

---

wifibroadcast-scripts/global_functions.sh
wifibroadcast-scripts/rx_functions.sh

The `VIDEO_WIFI_BITRATE` variable isn't always a bitrate, on 8812 cards it's an MCS index. We should leave that alone and simply use another variable for the OSD display.

Use separate variable for OSD hardware bitrate

---

wifibroadcast-osd/render.c
wifibroadcast-osd/render.h

The telemetry code for each protocol is already standardizing the value of the gps speed to KM/h so the 3.6 multiplication is already being done elsewhere.
This changes the function signature to properly document the unit of the variable.
This partially reverts 340b8aad858d807a31873a994b2ed4243703a27d
Closes: #263

Fix draw_TOTAL_DISTANCE, value is already KM/h

---

wifibroadcast-osd/Makefile
wifibroadcast-osd/flightmode.c
wifibroadcast-osd/flightmode.h
wifibroadcast-osd/render.c

Mavlink now uses the proper enums from the Mavlink library so we can guarantee they're correct just by looking at them. The other protocols use magic numbers, but they should be correct. 
VOT has no Chinese modes yet, but we can translate those in QOpenHD's translation system along with everything else anyway.
This adds non-Chinese LTM flight modes to the old OSD, it had the Chinese version and QOpenHD has english modes, so now the old OSD has both.

Use flight mode functions ported from QOpenHD

---

wifibroadcast-scripts/hotspot_functions.sh
wifibroadcast-scripts/rx_functions.sh
wifibroadcast-scripts/uplink_functions.sh

This uses named virtual serial ports to wire up mavlink router and the MSP connection on the ground, so that they aren't dependent on the "first come first serve" /dev/pts/X naming.
This also updates the connection between the telemetry system and mavlink-router so that it is no longer bottlenecked at 57600. The telemetry system itself is much faster, so this was just potentially slowing things down if someone had set 115200 on the air side.

Use named ports for MSP/Mavlink router, use 115200 baud to remove bottleneck

---

wifibroadcast-scripts/.profile

The scripts were using i2cdetect, which is the wrong way to do it.

Use vcgencmd to detect cameras in early boot

---

openhd-camera/openhdvid

This adds an `openhdvid` parameter called `--bitrate_record` or `-br` for short, which sets the recording bitrate separately from the main bitrate.
This is only intended for early experimentation, openhdvid will be replaced by the camera service in OpenHD 2.1 or 2.2, and that will have full support for recording.
To test it, set `-rec /home/pi/my_video.h264 -wr 1280 -hr 720 -br 12000000` (or any other resolution supported by the pi camera). This will record a 720p raw h264 file at 12Mbit, regardless of what the main stream bitrate is set to. Note that you must choose the recording parameters carefully: if the recording resolution is different than the stream resolution, the Pi will choose to add a resize step to one of them, which will add latency. You must also be sure not to exceed the …

Add recording bitrate setting to openhdvid

---

RemoteSettings/Air/RemoteSettingSyncAir.py
RemoteSettings/Ground/RemoteSettingsSync.py
wifibroadcast-scripts/configure_nics.sh
wifibroadcast-scripts/global_functions.sh
wifibroadcast-scripts/main.sh

We detect if an 8812 card is connected, in which case 5.8g band is available for SmartSync and normal use so we prioritize it, otherwise we use 2.4g.
If in any case we don't know what band is available or the settings file doesn't explicitly say "auto" or a specific frequency, we default to the same frequency we use by default anyway, 2412Mhz.

Add support for automating frequency selection

---

wifibroadcast-misc/LCD/MouseListener.c

This is the code responsible for adjusting the brightness when the old OSD is used with a touchscreen.
It's unlikely most people who have touchscreens are still using the old OSD, but this thing runs even when there's no touchscreen attached, and it was using 100% of a CPU core.

Prevent the old MouseListener from using 100% CPU

---

wifibroadcast-rc-Ath9k/rctx.cpp

The earlier code waited for a joystick before continuing initial setup, which prevented the UDP background thread from starting.
This also ensures that the process can exit when it wants to, previously the UDP thread was blocking on recvfrom().

Fix RC UDP and exit behavior

---

RemoteSettings/dhcpeventThread.sh
wifibroadcast-scripts/.profile
wifibroadcast-scripts/configure_nics.sh
wifibroadcast-scripts/global_functions.sh
wifibroadcast-scripts/main.sh
wifibroadcast-status/Makefile

This will forward all NIC setup events to the status microservice, including issues detecting or configuring NICs early during boot.
If something goes wrong the boot screen will remain visible with the last critical error shown, allowing users to know what happened just from looking at the screen. We will likely want to add a few more checks in this part of the system for other cases, but power issues and wifi card issues are covered already.
This PR also removes one of the sleep statements and uses a temporary signal to ensure the status service is ready before proceeding with early boot. This should be done with a systemd target soon instead, but it's ok for now.

Add early boot NIC status reporting

---

wifibroadcast-scripts/.profile

This was removed in 2.0.0rc2 due to a mixup during the change to use `vcgencmd` to detect multiple regular pi cameras and the hdmi-csi board

Ensure VEYE is detected in early boot

---

RemoteSettings/Ground/RemoteSettingsSync.py

These appear on the new boot screen, some of the messages were unnecessary and the state transition from "waiting for GPIO" to "waiting for air" was reverting once the UDP thread started.

Fix SmartSync state transitions and messages

---

wifibroadcast-osd/render.cpp
wifibroadcast-osd/settings.cpp

The color parser was disabled by accident, and the boolean values were set to match the default found in the settings file, which meant most of them were set to true if the setting was entirely missing ( or commented out). 
However, commenting out some of them is a valid way to disable them due to the way the older code was written, before we started reading the settings file instead of recompiling the OSD all the time. So we can't assume that a "missing" setting means it should use a default value.
This PR will also fix the OSD exiting if the users chosen font does not exist, which was not user friendly. We should show a warning in cases like that instead.
This PR also fixes the Mavlink AHI ladder range. There are 2 implementations of an AHI ladder in the old OSD code, the Mavlink …

Fix old OSD settings

---

wifibroadcast-scripts/osd_rx_functions.sh

People use plain video with no OSD, so we want to make sure that still works. At the moment the boot screen is accidentally remaining visible if the OSD is disabled.

Ensure OpenHDBoot stops even if OSD is disabled

---

wifibroadcast-osd/mavlink.cpp

There were a few stray `#ifdef` statements that hadn't been converted to runtime if-else statements.

Fix altitude and heading in old OSD

---

wifibroadcast-osd/ltm.cpp

This is basically just for the waypoint number, which is the only info the old OSD can use. It may not end up being useful if people are running Mavlink for missions anyway, but at least it will be implemented.

Add support for LTM N frame in old OSD

---

config/openhd-settings-1.txt

The mp4 container generally deals with h264 video a little better than avi, which is not really designed for it.

Switch default video save format to mp4

---

wifibroadcast-scripts/tx_rx_functions.sh

This increases the space to 1/3 + 30mb, which works out like this:
Pi3a+: (512mb total - 128mb GPU) / 3 = 128, + 30mb = 158mb
Pi3b+: (1024mb total - 128mb GPU) / 3 = 298, + 30mb = 328mb
Pi4b: (2048mb total - 128mb GPU) / 3 = 640, + 30mb = 670mb
At an average bitrate of 5mbit, the pi3a+ could record 5:16, the
pi3b+ could record 10:56, and the 2gb pi4 could record 22:20. A pi4
4gb could record more than anyone is likely to fly.
We should probably disable recording on the pi3a+ so that it
doesn't cause problems, nobody is going to want to record for just 5
minutes anyway.
We're going to add the ability to record to USB sticks and fix the
microsd recording as well but people may still want to record to
ram since it is guaranteed to be reliable and not affect other things,
so long as the …

Increase video recording space in memory

---

after-install.sh
package.sh
wifibroadcast-scripts/video_save_functions.sh

This PR does the following:
* Uses a unique folder name for each set of files saved to the usb drive, based on the date/time when saving started
* The date will almost always be wrong until we allow QOpenHD to set it based on correct phone time, and/or let the microservice code set it based on GPS time coming from the flight controller
* Shows a warning on the OSD when recording space is full
* Corrects the log levels of the recording status messages
* Shows a progress message during save
* Restarts the rssi logger when saving to USB finishes
* Seems like a simple omission, it wasn't be restarted before so it only worked for a single recording until reboot
* Remove the `usbmount` package as a dependency of the openhd package
* Automounted the USB drive twice and made it difficult to …

Update the video save system

---

wifibroadcast-osd/render.cpp

It is supposed to show trends. The altitude one works correctly. 
The speed and yaw have bugs because the mavlink messages they read aer in a global motion context, instead of local. 
The fix is to convert the global x y motion vectors to a local context x y motion vector.

Remove speed trend and yaw trend from osd

---

openhd-camera/openhdvid

Adding a function to allow timelaps pictures to be recorded on the air side.
Options to put into the EXTRAPARAMS of the openhd-settings-1.txt file are : 
- --timelaps /home/pi/timelaps.jpeg => Path to saved image. Extension of file is not used. We are saving images in YUV format
- -wtl 2028 => Width
- -htl 1080 => Height
- -stl 1 => Time in seconds between each capture

Add Timelaps Air function

---

config/openhd-settings-1.txt
wifibroadcast-scripts/tx_functions.sh

This setting was added in with the other lot as it looked to be missing. From reading the documentation it looks like this needs to be set before detection so it is being removed again to see if it fixes issues with startup.

Remove videoformat from VEYE

---

wifibroadcast-scripts/.profile
wifibroadcast-scripts/tx_functions.sh

Added in a command run run the camera config for VEYE cams prior to detection.

Run camera config

---

after-install.sh
openhd-common/openhd-wifi.hpp
openhd-interface/src/streams.cpp
openhd-power/Makefile
openhd-power/inc/powermicroservice.h
openhd-power/openhd_power.service
openhd-power/src/main.cpp
openhd-power/src/powermicroservice.cpp
openhd-status/Makefile
openhd-status/Makefile_old
openhd-status/inc/statusmicroservice.h
openhd-status/openhd_status.service
openhd-status/src/main.cpp
openhd-status/src/statusmicroservice.cpp
openhd-system/src/wifi.cpp
openhd-video/src/gstreamerstream.cpp
package.sh

This pull request contains the following fixes:
* Fix invalid gstreamer stream syntax (general)
* Fix invalid parameter for nvarguscamerasrc gStreamer element (jetson Nano)
* Fix bad call to wfb_tx/wfb_rx when multiple injection-capable wifi interfaces are available
* Use proper keys from rx/tx keypair for telemetry streams
And the following feature additions:
* Initial implementation of Power microservice. It acknowledges and executes restart/shutdown commands sent from the UI (QOpenHD)
* Initial implementation of Status microservice (as was prepared by Stephen: https://github.com/OpenHD/OpenHDMicroservice ). Key feature is that it forwards qstatus messages over mavlink so they are now handled by QOpenHD.
* Support for ath9k driver. For non-USB Atheros cards. Testing on different cards …

Jetson Nano compatibility, bugfixes, power&status microservices

---

openhd-power/Makefile
openhd-status/Makefile
openhd-video/Makefile
openhd-video/inc/control.h

Signal2 is a header library and should not require building... This is all caused by pump and boost signal depreciation in ubuntu focal

Migrate to boost signal2

---

openhd-video/src/control.cpp

Signals2 is a header library and should not require building... This is all caused by pump and boost signal depreciation in ubuntu focal

Migrate to boost signal2 continued

---

package.sh

Bullseye requires different packages to buster so they are being separated.
Bullseye also uses the kms display driver not the fkms so this is only being added to buster.

different bullseye packages

---

.drone.yml

The triggers were workingi n the sense that commits would not trigger a build and only pull requests would. But then it was breaking something in the upload to cloudsmith. 
Checking deb package upload parameters ... ERROR
Failed to validate upload parameters! (status: 401 - Unauthorized)
Detail: Invalid token.

Remove trigger experiment. Break upload to cloudsmith

---

openhd-system/src/cameras.cpp

Adding the code that will recognise a veye cam as valid and start as Air.

add veye camera recognition and settings

---

config/config.txt

Now put against the 2.0 branch as requested.
Many new people hop on onto telegram asking why their RPI 4 isn't booting. Then they are told, add `total_mem=3072` to their config.txt This should make the initial setup less frustrating and user friendly.

Add config line regarding rpi 4's that won't boot

---

OpenHD/CMakeLists.txt

fix building error with fs not found in debian
```shell
[ 94%] Linking CXX executable test_interface
[100%] Linking CXX executable test_common_util
/usr/bin/ld: libOHDInterfaceLib.a(WifiCards.cpp.o): in function `generateSettingsDirectoryIfNonExists()':
WifiCards.cpp:(.text+0x2420): undefined reference to `std::filesystem::create_directory(std::filesystem::__cxx11::path const&)'
/usr/bin/ld: libOHDInterfaceLib.a(WifiCards.cpp.o): in function `findOrCreateSettingsDirectory(bool)':
WifiCards.cpp:(.text+0x2850): undefined reference to `std::filesystem::create_directory(std::filesystem::__cxx11::path const&)'
/usr/bin/ld: libOHDInterfaceLib.a(WifiCards.cpp.o): in function `std::filesystem::exists(std::filesystem::__cxx11::path const&)': …
```

fix building error with fs not found in debian
